### ISSUE TITLE
JSON-LD checker does not resolve structured arrays in schema files

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/traceability-vocab#89] opened 2021-02-10 18:44 UTC
The schema referenced below does not resolve and check properly in the js-vc-ci-tests. I need to have the following context array in the test generator file for the EcommercePackingListRegistrationCredential for the test to pass.
```
[
        'https://www.w3.org/2018/credentials/v1',
        'https://w3id.org/traceability/v1',
        { "orderNumber": "https://schema.org/orderNumber" },
        { "productInOrder": "https://schema.orgproductID" }
    ]
```

It tells me that "orderNumber" and "productInOrder" are not defined in the context.

Even though I have 

```
"EcommercePackingListRegistrationCredential": {
      "@id": "https://w3id.org/traceability#EcommercePackingListRegistrationCredential",
      "@context": {
        "packageItems": {
          "@id": "https://schema.org/ItemList"
        },
        "certificateName": {
          "@id": "https://schema.org/name"
        }
      }
    }
```

in the traceability context file.

Note that in the schema for the EcommercePackingListRegistrationCredential, `packageItems` is of the type `array` where each array entry MUST is a list  "orderNumber" and "productInOrder", where "productInOrder" is an array itself.
```
{
    "$id": "https://w3id.org/traceability/schemas/EcommercePackingListRegistrationCredential.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"EcommercePackingListRegistrationCredential\", \"@id\": \"https://w3id.org/traceability#EcommercePackingListRegistrationCredential\"}",
    "title": "EcommercePackingListRegistrationCredential",
    "description": "Ecommerce Packing List Registration Credential",
    "type": "object",
    "required": [
        "@context",
        "packageItems",
        "certificateName"
    ],
    "properties": {
        "@context": {
            "type": "array"
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array"
                }
            ]
        },
        "packageItems": {
            "$comment": "{\"term\": \"packageItems\", \"@id\": \"https://schema.org/ItemList\"}",
            "title": "packageItems",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "orderNumber": {
                        "$comment": "{\"term\": \"orderNumber\", \"@id\": \"https://schema.org/orderNumber\"}",
                        "title": "orderNumber",
                        "description": "The seller specific Order VC ID",
                        "type": "string"
                    },
                    "productInOrder": {
                        "$comment": "{\"term\": \"productInOrder\", \"@id\": \"https://schema.org/productID\"}",
                        "title": "productInOrder",
                        "description": "Product VC IDs included in the order",
                        "type": "array"
                    }
                }
            }
        },
        "certificateName": {
            "$comment": "{\"term\": \"certificateName\", \"@id\": \"https://schema.org/name\"}",
            "title": "certificateName",
            "description": "Specific name of issued packing list registration certificate",
            "type": "string"
        }
    },
    "additionalProperties": false,
    "examples": []
}
```

Also, note that this error does not appear when I run the schema tests where the schema test generator is basically identical to the credential test generator. 

cc @OR13

**Comment by OR13** [comment] 2021-02-10 18:53
hmm, sad code formatting... can we maybe provide a small well formatted JSON example that can be tested.

[For Example](https://www.jsonld-checker.com/?json=%257B%250A%2520%2520%2522%2540context%2522%253A%2520%255B%250A%2520%2520%2520%2520%2522https%253A%252F%252Fw3id.org%252Ftraceability%252Fv1%2522%250A%2520%2520%255D%252C%250A%2520%2520%2522type%2522%253A%2520%2522Person%2522%252C%250A%2520%2520%2522firstName%2522%253A%2520%2522Jefferey%2522%252C%250A%2520%2520%2522lastName%2522%253A%2520%2522Collier%2522%252C%250A%2520%2520%2522email%2522%253A%2520%2522Raymundo_Hodkiewicz%2540example.com%2522%252C%250A%2520%2520%2522phoneNumber%2522%253A%2520%2522555-834-3001%2522%252C%250A%2520%2520%2522worksFor%2522%253A%2520%257B%250A%2520%2520%2520%2520%2522type%2522%253A%2520%2522Organization%2522%252C%250A%2520%2520%2520%2520%2522name%2522%253A%2520%2522Bailey%2520Inc%2522%252C%250A%2520%2520%2520%2520%2522description%2522%253A%2520%2522Synchronised%2520intermediate%2520product%2522%252C%250A%2520%2520%2520%2520%2522address%2522%253A%2520%257B%250A%2520%2520%2520%2520%2520%2520%2522type%2522%253A%2520%2522PostalAddress%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522streetAddress%2522%253A%2520%252289388%2520Chaz%2520Parks%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522addressLocality%2522%253A%2520%2522Rohanhaven%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522addressRegion%2522%253A%2520%2522Connecticut%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522postalCode%2522%253A%2520%252224271-1387%2522%252C%250A%2520%2520%2520%2520%2520%2520%2522addressCountry%2522%253A%2520%2522British%2520Indian%2520Ocean%2520Territory%2520%28Chagos%2520Archipelago%29%2522%250A%2520%2520%2520%2520%257D%252C%250A%2520%2520%2520%2520%2522email%2522%253A%2520%2522Caterina11%2540example.net%2522%252C%250A%2520%2520%2520%2520%2522phoneNumber%2522%253A%2520%2522555-584-8727%2522%250A%2520%2520%257D%252C%250A%2520%2520%2522jobTitle%2522%253A%2520%2522District%2520Solutions%2520Manager%2522%250A%257D)

**Comment by Therecanbeonlyone1969** [comment] 2021-02-10 19:01
apologies for the formatting ... github does not have great md formatting ... here is an example generated by the schema. @OR13 ... and the json-ld checker online balks because the schema is not yet in the context file in the repo. 

```
{
      "@context": [
        "https://w3id.org/traceability/v1"
      ],
      "type": "EcommercePackingListRegistrationCredential",
      "packageItems": [
        {
          "orderNumber": "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
          "productInOrder": [
            "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
            "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
            "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
            "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58599e"
          ]
        }
      ],
      "certificateName": "ACME Ecommerce Packing List Registration Certificate"
    }
```

**Comment by mprorock** [comment] 2021-02-10 19:04
> and the json-ld checker online balks because the schema is not yet in the context file in the repo.

Not sure a good way around this with the online checker - this will always be the case if you are pointing at a context that doesn't yet have your object in it, until a PR is in and up and tested, unless @OR13 is aware of something i am not

**Comment by Therecanbeonlyone1969** [comment] 2021-02-10 19:08
> > and the json-ld checker online balks because the schema is not yet in the context file in the repo.
> 
> Not sure a good way around this with the online checker - this will always be the case if you are pointing at a context that doesn't yet have your object in it, until a PR is in and up and tested, unless @OR13 is aware of something i am not

It can be done locally and as I said the schema validates locally just fine but after it is added to the context, the checker for the credential test balks

**Comment by mprorock** [comment] 2021-02-11 01:33
running into similar things on our side with some tests, so can definitely reproduce - we are taking a look at it.  There may be a few things additionally that the checker is not catching, etc.

**Comment by OR13** [comment] 2021-02-11 16:40
You can copy the terms you are about to get added into the context, like this:

```json
{
      "@context": [
        "https://w3id.org/traceability/v1",
        { "newTerm": "https://schema.org/Property" }
      ],
      "type": "EcommercePackingListRegistrationCredential",
      "packageItems": [
        {
          "orderNumber": "https://vc.example.com/?queryID=AB06f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58597a",
          "productInOrder": [
            "https://vc.example.com/?queryID=6206f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
            "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
            "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58598a",
            "https://vc.example.com/?queryID=7306f1f744a781480c521902a1a1dbf5f1d01e7ea21daf483e7668817e58599e"
          ]
        }
      ],
      "certificateName": "ACME Ecommerce Packing List Registration Certificate"
    }
    }
    ```
    
    locally, you can generate the new JSON-LD context and the document loader will use your local version:
    
    https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/js-vc-ci-tests/services/documentLoader.js#L19

**Comment by OR13** [comment] 2021-02-11 16:44
other examples:

```
{
  "@context": [
    {
      "type": "@type",
      "IntentToSell": "https://w3id.org/traceability#IntentToSell",
      "seller": "https://w3id.org/traceability#Entity",
      "Person": "https://schema.org/Person",
      "firstName": "https://schema.org/givenName",
      "lastName": "https://schema.org/familyName"
    }
  ],
  "type": "IntentToSell",
  "seller": {
    "type": "Person",
    "firstName": "Colten",
    "lastName": "Welch"
  }
}
```

```
{
  "@context": [
       "https://w3id.org/traceability/v1"
  ],
  "type": "IntentToSell",
  "seller": {
    "type": "Person",
    "firstName": "Colten",
    "lastName": "Welch"
  }
}
```

its often helpful to replace the context URL with an object, so you can see everything in 1 place...

**Comment by Therecanbeonlyone1969** [comment] 2021-02-13 21:57
@or13 @mprorock ok ... so I found a way such that the schema tests pass even with a strict setting. You need to reference a definition in the schema under the right property and since the property is an array you need to list the items, and then it works -- see the working schema files below. Ideally, that should not have to be done but it is a legal schema and it works. There is still a subtle bug in the schema checker that does not recognize the props when included directly. You wanna keep the issue open?

```
{
    "$id": "https://w3id.org/traceability/schemas/EcommercePackingListRegistrationCredential.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"EcommercePackingListRegistrationCredential\", \"@id\": \"https://w3id.org/traceability#EcommercePackingListRegistrationCredential\"}",
    "title": "EcommercePackingListRegistrationCredential",
    "description": "Ecommerce Packing List Registration Credential",
    "definitions": {
        "packinglistorder": {
            "$id": "#packinglistorder",
            "type": "object",
            "properties": {
                "orderNumber": {
                    "$comment": "{\"term\": \"orderNumber\", \"@id\": \"https://schema.org/orderNumber\"}",
                    "title": "orderNumber",
                    "description": "The seller specific Order VC ID",
                    "type": "string"
                },
                "productInOrder": {
                    "$comment": "{\"term\": \"productInOrder\", \"@id\": \"https://schema.org/productID\"}",
                    "title": "productInOrder",
                    "description": "Product VC IDs included in the order",
                    "type": "array"
                }
            },
            "required": [
                "orderNumber",
                "productInOrder"
            ]
        }
    },
    "type": "object",
    "properties": {
        "@context": {
            "type": "array"
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array"
                }
            ]
        },
        "packageItems": {
            "$comment": "{\"term\": \"packageItems\", \"@id\": \"https://schema.org/ItemList\"}",
            "title": "packageItems",
            "type": "array",
            "items": {
                "$ref": "#packinglistorder"
            }
        },
        "certificateName": {
            "$comment": "{\"term\": \"certificateName\", \"@id\": \"https://schema.org/name\"}",
            "title": "certificateName",
            "description": "Specific name of issued packing list registration certificate",
            "type": "string"
        }
    },
    "required": [
        "@context",
        "type",
        "packageItems",
        "certificateName"
    ],
    "additionalProperties": false,
    "examples": []
}
```

**Comment by Therecanbeonlyone1969** [comment] 2021-02-13 22:02
oh and I added "orderNumber" and "productInOrder" to the top section in the context file by adding them to the help.js file. The context is otherwise still not correctly resolved in the credential issuance and verification tests. With that addition, the credential test of the problematic Packinglist credential passes without a problem. @OR13 @mprorock

**Comment by OR13** [comment] 2021-02-17 16:09
I believe this may now be fixed...

**Comment by OR13** [comment] 2021-02-17 16:10
can we provide a minimal example for https://www.jsonld-checker.com/ to confirm?

**Comment by mprorock** [comment] 2021-03-08 02:06
i believe this is fixed now as well.  if we can reproduce elsewhere due to other items, we can open a new issue specific to that

**Closed by mprorock** 2021-03-08 02:06 UTC
Labels: bug
