### ISSUE TITLE
Add CredentialStatus to BankAccount VC example

### ISSUE THREAD

**Issue by adewaleafolabi** [w3c-ccg/traceability-vocab#819] opened 2023-06-20 17:00 UTC
This issue is focused on updating the Bank Account Virtual Card to incorporate the 'credentialStatus' as outlined in the StatusList2021Entry specification.

**Comment by BenjaminMoe** [comment] 2023-10-24 17:53
Is a dupe of https://github.com/w3c-ccg/traceability-vocab/issues/816?

**Comment by mkhraisha** [comment] 2024-03-05 18:13
Closing as dupe of #816

**Closed by mkhraisha** 2024-03-05 18:13 UTC
