### ISSUE TITLE
DEVELOPMENT.md#ontology-structure should be changed to YAML example

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#311] opened 2022-02-23 10:42 UTC
This still shows our earlier JSON ways:
https://github.com/w3c-ccg/traceability-vocab/blob/main/DEVELOPMENT.md#ontology-structure

**Comment by BenjaminMoe** [comment] 2022-07-13 16:45
I think this is effectively a duplicate of: https://github.com/w3c-ccg/traceability-vocab/issues/307

**Closed** 2022-07-26 18:06 UTC
Labels: pending-close
