### ISSUE TITLE
Versioning on schemas and test vectors

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#65] opened 2021-01-26 17:33 UTC
We've been exploring the possibility of pulling these schemas and test vectors programmatically to validate and use as models in our app.  In order to do this safely it would make sense to have versioning on this repo.  Any thoughts/concerns/etc. on doing this?

**Comment by mprorock** [comment] 2021-01-29 01:52
I think we should plan on at least pinning a version prior to the upcoming plugfest for vc-http-api as this repo will likely serve as the payload for the various supply chain VCs.  right now - a first release cutoff data will likely be towards the end of February. @OR13 any input from your side on this?

**Comment by OR13** [comment] 2021-02-01 19:10
hmm... yes

I think we need to start establishing perma links for pinned versions.

here is how that should work:

We cut github release for the version and create a perma link it github pages:

https://w3c-ccg.github.io/traceability-vocab/v1/

We then update w3id.org .htaccess to point to the pinned version:

https://w3id.org/traceability/v1 -> https://w3c-ccg.github.io/traceability-vocab/v1/traceability-v1.jsonld
https://w3id.org/traceability/v1/ -> https://w3c-ccg.github.io/traceability-vocab/v1/index.html

We confirm the expected behavior for JSON-LD:

https://w3id.org/traceability/v1 -> redirects to a JSON-LD context file:
https://w3id.org/traceability/v1#Organization -> html anchor tag describing organization.

Here is an example of this from elsewhere:

https://w3id.org/security/v1 -> https://w3c-ccg.github.io/security-vocab/contexts/security-v1.jsonld
https://w3id.org/security#Ed25519Signature2018 -> https://w3c-ccg.github.io/security-vocab/#Ed25519Signature2018

Note the fragment persists across the redirect.

Also note that security context is append only... but I think its a mistake not to cut a version of the html when we cut a version of the contexts and schemas.

**Comment by msporny** [comment] 2021-02-02 15:16
> We then update w3id.org .htaccess to point to the pinned version:
> 
> https://w3id.org/traceability/v1 -> https://w3c-ccg.github.io/traceability-vocab/v1/traceability-v1.jsonld
> https://w3id.org/traceability/v1/ -> https://w3c-ccg.github.io/traceability-vocab/v1/index.html

I'm going to suggest that the above is an anti-pattern that will result in versioned vocabularies... which you really don't want to impose on Web developers, because it breaks all the semantics... all of a sudden you have /versions/ of words. To draw an analogy... that's like saying "You're saying the word 'hello', but do you mean 1850s hello, 1910s hello, or 2020s hello? My software only understands the 1850s and 1910s hello".

Version JSON-LD Contexts... that's fine. Don't version vocabularies -- you're creating a ton of complexity when you do that. Sure, v1 feels great and easy to understand... v2 will feel a bit worse... v3, v4, and v5 will feel absolutely horrible because people will have deployed with v2, v3, and v4 into production and you will have to support all variations where people are mixing v2 and v3 vocabulary terms (and changing the meaning ever so slightly between versions).

**Comment by mprorock** [comment] 2021-02-02 16:58
@msporny EPCIS uses versioning in exactly the manner discussed by @OR13 and they are kindof the gold standard for vocabulary in supply chain.  The main reason for this versioning, is that it lets those of us working with enterprise customers in supply chain "pin" a version for integration testing, etc.  This versioning approach also lets us then reliably generate statically typed stubs and code, test against, and interoperate with others using payloads from this repo, even if we do not necessarily work in or with their specific commodity which will be highly important for those of us who wish to be able to add a layer of validation in our interop testing that extends to payloads in addition to just VC validation. Hard versioning is important enough, that I have received flat refusals to integrate in any production code a vocabulary that is not versioned by multiple senior developers within various customer facing scenarios.

Key guidelines around versioning will have to be discussed, but likely a standard approach where minor versions must be non-breaking and backwards compatible, with major versions permitting breaking changes.  If we do our jobs right, v1 will have all core VC payloads being used with the vc-http-api by supply chain companies participating in the upcoming plugfest, and future major version increments will occur on a frequency of no more than annually.

**Comment by OR13** [comment] 2021-02-02 17:06
https://github.com/perma-id/w3id.org/tree/master/traceability

^ where the redirects need to be implemented.

**Comment by msporny** [comment] 2021-02-02 17:06
@mprorock wrote:
> The main reason for this versioning, is that it lets those of us working with enterprise customers in supply chain "pin" a version for integration testing, etc. This versioning approach also lets us then reliably generate statically typed stubs and code, test against, and interoperate with others using payloads from this repo

Yes, we work with supply chain customers too. We're talking past each other. It's completely fine and expected to version the JSON-LD Context using the mechanism you describe above.

It is going to create a nightmare for you to version the vocabulary URLs. To put a finer point on it, it's fine for you to do this:

> https://w3id.org/traceability/v1 
> https://w3id.org/traceability/v1.1
> https://w3id.org/traceability/v2 

It is going to be a nightmare for YOU if you do this (because this creates three new concepts all called "Organization"):

> https://w3id.org/traceability/v1/#Organization
> https://w3id.org/traceability/v1.1/#Organization
> https://w3id.org/traceability/v2/#Organization

**Comment by OR13** [comment] 2021-02-02 17:15
https://w3id.org/traceability#Organization -> latest version
https://w3id.org/traceability/v1-> latest context

https://w3id.org/traceability/v1#Organization ->v1 version

IMO its night a nightmare, and all the term IRIs that are signed over should follow cool uris, aka ... always use the "latest".

**Comment by msporny** [comment] 2021-02-02 17:20
Which URL are you using in the signed triples? https://w3id.org/traceability#Organization or https://w3id.org/traceability/v1#Organization?

**Comment by OR13** [comment] 2021-02-02 17:35
"https://w3id.org/traceability#Organization" aka always sign over latest.... the fact that http version of that vocab exists and preserved is for audibility / convenience... not semantic disambiguity, imo.

at least thats my proposal.

**Comment by OR13** [comment] 2021-02-02 17:36
btw... we really need to fix out anchor tags... that link should work.

**Comment by msporny** [comment] 2021-02-02 17:47
> @msporny "https://w3id.org/traceability#Organization" aka always sign over latest.... the fact that http version of v1 vocab exists and is preserved is for audibility / convenience... not semantic disambiguity, imo.

Do you have some triples/quads to share? I think I agree with what you're saying above (v1 vocab is for convenience only -- never for signing)... but I want to make sure we're crystal clear about this 'cause the way things are phrased in some of these comments could mean the opposite of what I think you're saying.

**Comment by msporny** [comment] 2021-02-02 17:55
>  I think its bad idea to make unstable stuff append only, when it has low adoption... I want to be able to cut / break / force updates until we get adoption that prevents that.

Unfortunately, that adoption usually happens when you don't want it to happen. Case in point: the Ed25519Signature2018 cryptosuite... it was supposed to be a stop gap until we published Ed25519Signature2020, and then we wanted everyone to drop support for 2018 and use either Ed25519Signature2020 or JsonWebSignature2020 instead. Except that we're about to do in the DID spec is memorialize publicKeyBase58 (and not publicKeyMultibase), and Ed25519Signature2018. :(

When things become popular, they tend to ossify at a rate that is problematic to the ecosystem. People won't wait for you to determine low/high adoption... they'll just ship stuff into production and then object when you want to make breaking changes that would make the ecosystem simpler.

**Comment by OR13** [comment] 2021-02-02 17:57
@msporny sorta off topic, but .... it's not too late to reserve `publicKeyMultibase` in did core v1... if you really intend to deprecate base58 you should fight for that or your existing customers will be sad...

**Comment by msporny** [comment] 2021-02-02 17:58
> For both v1 and v2 nquads would be

Got it, thank you -- we're on the same page in general.

I'll be interested to hear how updating a popular vocabulary goes... it often happens on a continuum, and it's difficult (but not impossible) to cut major versions that don't lose some of the history. We depend on github repos for this, so that usually works out for those that want to know when a particular constraint or word changed.

**Comment by OR13** [comment] 2021-02-02 18:00
Probably the best example out there today....

https://github.com/schemaorg/schemaorg/tree/main/data/releases

yikes...

**Comment by msporny** [comment] 2021-02-02 18:00
> @msporny sorta off topic, but .... it's not too late to reserve publicKeyMultibase in did core v1... 

Yes, I know -- new feature, many people would object (even though it would be the best thing for the global ecosystem)

> if you really intend to deprecate base58 you should fight for that or your existing customers will be sad...

We'll probably just end up supporting 2018 and 2020 -- it'll add complexity to the ecosystem temporarily while we float the notion of deprecating publicKeyBase58 in favor of publicKeyMultibase over the next year or two.

**Comment by OR13** [comment] 2021-02-02 18:04
See also: https://github.com/schemaorg/schemaorg/issues/2805

**Comment by OR13** [comment] 2021-04-28 14:15
I don't think we ever managed to "ship a stable version" I suggest we continue to treat v1 as unstable, until people scream, and help resolve this.

**Comment by OR13** [comment] 2021-05-11 18:14
Discussed on call, recommend closing, and keeping the v1 unstable...

**Comment by OR13** [comment] 2021-06-15 18:17
Need a warning added to the spec before this can be cclosed.

**Comment by nissimsan** [comment] 2021-08-31 18:15
Assign me

**Comment by mprorock** [comment] 2022-01-18 19:16
Per call: can close now that docs are in place and CI is running

**Closed by mprorock** 2022-01-18 19:16 UTC
Labels: pending-close
